# Generated by Django 4.1.2 on 2022-11-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
