# Generated by Django 4.1.2 on 2022-11-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_feedbacks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
